"""
Workflow module for generating and validating Python code using Mistral AI agent.

This module provides functionality to interact with a Mistral AI agent to generate
Python functions and test cases, then validate them through execution.
"""

import re
import os
import argparse
from dotenv import load_dotenv
from mistralai import Mistral

# Load environment variables from .env
load_dotenv()

# Get the Mistral API key from environment variables
api_key = os.getenv("MISTRAL_API_KEY")
if not api_key:
    raise ValueError("Mistral API key not found in environment variables.")

client = Mistral(api_key=api_key)
AGENT_ID = "ag:abd0e357:20250304:basicagent:b3fa2795"

def run_python_agent(query):
    """
    Sends a user query to a Python agent and returns the response.
    Args:
        query (str): The user query to be sent to the Python agent.
    Returns:
        str: The response content from the Python agent.
    """
    print("### Run Python agent")
    print(f"User query: {query}")
    try:
        response = client.agents.complete(
            agent_id=AGENT_ID,
            messages=[
                {
                    "role": "user",
                    "content": query
                },
            ]
        )
        result = response.choices[0].message.content
        return result
    except (ConnectionError, TimeoutError, ValueError) as e:
        print(f"Request failed: {e}. Please check your request.")
        return None

def extract_pattern(text, pattern):
    """
    Extracts a pattern from the given text.
    Args:
        text (str): The text to search within.
        pattern (str): The regex pattern to search for.
    Returns:
        str: The extracted pattern or None if not found.
    """
    match = re.search(pattern, text, flags=re.DOTALL)
    if match:
        return match.group(1).strip()
    return None

def extract_code(result):
    """
    Extracts Python function and test case from the response content.
    Args:
        result (str): The response content from the Python agent.
    Returns:
        tuple: A tuple containing the extracted Python function,
               test function, and a retry flag.
    """
    retry = False
    print("### Extracting Python code")
    python_function = extract_pattern(
        result, r'## Python function(.*?)## Test case'
    )
    if not python_function:
        retry = True
        print("Python function failed to generate or wrong output format. "
              "Setting retry to True.")
    print("### Extracting test case")
    test_function = extract_pattern(result, r'## Test case(.*?)```')
    if not test_function:
        retry = True
        print("Test function failed to generate or wrong output format. "
              "Setting retry to True.")
    return python_function, test_function, retry

def check_code(python_function, test_function):
    """
    Executes the Python function and its test case, and checks for any errors.
    Args:
        python_function (str): The Python function to be executed.
        test_function (str): The test case to be executed.
    Returns:
        bool: A flag indicating whether the code execution needs to be retried.
    Warning:
        This code is designed to run code that's been generated by a model,
        which may not be entirely reliable. It's strongly recommended to run
        this in a sandbox environment.
    """
    retry = False
    try:
        exec(python_function)  # pylint: disable=exec-used
        print("Code executed successfully.")
        try:
            exec(test_function)  # pylint: disable=exec-used
            print("Code passed test case.")
        except (AssertionError, ValueError, TypeError, NameError) as e:
            print(f"Test failed: {e}")
            retry = True
            print("Setting retry to True")
    except (SyntaxError, NameError, TypeError, ValueError) as e:
        print(f"Code failed: {e}")
        retry = True
        print("Setting retry to True")
    return retry

def run_workflow(query):
    """
    Runs the complete workflow to generate, extract, and validate Python code.
    Args:
        query (str): The user query to be processed.
    """
    print("### ENTER WORKFLOW")
    i = 0
    max_retries = 3
    retry = True  # just to get it started
    while i < max_retries and retry:
        print(f"TRY # {i}")
        i += 1
        result = run_python_agent(query)
        python_function, test_function, retry = extract_code(result)
        retry = check_code(python_function, test_function)
    if not retry:
        print(f"Validated Python function: ```{python_function}```")
    print("### EXIT WORKFLOW")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run the workflow to generate and validate Python code."
    )
    parser.add_argument("query", type=str,
                        help="The user query to be processed.")
    args = parser.parse_args()
    run_workflow(args.query)
